export type DataObject = {
  Balance: number,
  CharactersRatio: number,
  ErrorKeyRatio: number,
  SnAppChange: number,
  SnChars: number,
  SnDirectionKeys: number,
  SnDoubleClicked: number,
  SnErrorKeys: number,
  SnKeyStrokes: number,
  SnLeftClicked: number,
  SnMouseAct: number,
  SnMouseDistance: number,
  SnRightClicked: number,
  SnShortcutKeys: number,
  SnSpaces: number,
  SnSpecialKeys: number,
  SnTabfocusChange: number,
  SnWheel: number,
  Stress: number,
  timestamp: string
}
